### PR TITLE
Add :caption and :download options to Kino.Mermaid

### PR DESCRIPTION
**Pull request by christhekeele**
Originating from [this thread on the forums](https://elixirforum.com/t/how-can-kino-be-used-to-export-a-mermaid-image-in-livebook/66665), this PR:

- Gives `Kino.Mermaid` diagrams an optional on-hover download button
- Makes the rendered diagram an HTML5 `<figure>`
  - Uses flexbox to horizontally center the rendered diagram
  - Allows for an optional `<figcaption>` to describe the rendered diagram

#### Images

- Flexbox-centered `<figure>` (chrome browser defaults stylesheets adds a `1em` margin to them)

  Screenshot 2024-10-13 at 3 37 43 PM

- Figure with caption (styled roughly after Livebook's `.info-box` CSS)

  Screenshot 2024-10-13 at 3 37 16 PM

- Flexbox-centering in a grid

  Screenshot 2024-10-13 at 3 37 16 PM

- Download button with title
 
  Screenshot 2024-10-13 at 3 39 10 PM

- Download with custom filename

  Screenshot 2024-10-13 at 3 44 23 PM
  Screenshot 2024-10-13 at 3 44 41 PM

- Default captions for `Kino.Process.app_tree` example

  Screenshot 2024-10-13 at 5 27 37 PM

- Default captions for named `Kino.Process.sup_tree` example

  Screenshot 2024-10-13 at 5 28 04 PM

- Default captions for pid `Kino.Process.sup_tree` example

  Screenshot 2024-10-13 at 5 27 46 PM

- Default captions for `Kino.Process.seq_trace` example

  Screenshot 2024-10-13 at 5 36 20 PM

  Screenshot 2024-10-13 at 5 36 28 PM

### CODE REVIEW

**Review by josevalim — APPROVED** [review]

**Comment by christhekeele** [comment]
Note: I did not check in all the changes to the bundled mermaid assets, as there is a lot of churn there. Is that handled in the package publication process, or should I push the changes to `lib/assets` up too?

**Comment by jonatanklosko** [comment]
@christhekeele thanks for the PR! I updated the styling and simplified some of the options :)

**Comment by jonatanklosko** [comment]
> Note: I did not check in all the changes to the bundled mermaid assets, as there is a lot of churn there. Is that handled in the package publication process, or should I push the changes to lib/assets up too?

Bundling in the PR is fine, I bundle before or after merging anyway :) (we want to keep git in sync, in case someone installs the package from GitHub)

**Comment by christhekeele** [comment]
I did notice a couple of possible UI regressions with the updated styling, @jonatanklosko , thought I'd report them here.

---

Large diagrams now get very small—unsure if this is intentional? (Partially mitigated by the full diagram being downloadable, now).

For example, the `Kino.Process.seq_trace/1` example

```elixir
{_, diagram} = Kino.Process.seq_trace(fn ->
  {:ok, agent_pid} = Agent.start_link(fn -> [] end)
  Process.monitor(agent_pid)

  1..2
  |> Task.async_stream(
    fn value ->
      Agent.get(agent_pid, fn value -> value end)
      100 * value
    end,
    max_concurrency: 3
  )
  |> Stream.run()

  Agent.stop(agent_pid)
end)

diagram
```

with new styling it renders illegibly for me, like:

Screenshot 2024-10-15 at 11 49 42 AM

whereas in the current release of Kino, it renders full-width:

Screenshot 2024-10-15 at 11 53 36 AM

---

Additionally, vanilla unstyled diagrams have gotten... chonkier? post-update. New:

Screenshot 2024-10-15 at 11 55 19 AM

old:

Screenshot 2024-10-15 at 11 54 33 AM

---

Unsure if these are undesirable or not, just thought I'd mention them!

OSX, recent Chrome

**Comment by jonatanklosko** [comment]
@christhekeele thanks, the diagram width shrinking is unexpected, I've just fixed on main. The second is an expected change in mermaid v11, which I updated on main after this PR :)

**Pull request merged**
