### PR TITLE
Support toggling smart cell editor visibility

### PR DESCRIPTION
**Pull request by jonatanklosko**
https://github.com/user-attachments/assets/a2661ee7-1797-4e6b-94f0-6111aac07e0c

<details><summary>Source</summary>

```elixir
defmodule SmartCellWithEditorToggle do
  use Kino.JS
  use Kino.JS.Live
  use Kino.SmartCell, name: "Smart cell with editor toggle"

  @impl true
  def init(attrs, ctx) do
    source = attrs["source"] || ""
    ctx = assign(ctx, source: source, visible: false)
    {:ok, ctx, editor: [source: source, visible: false]}
  end

  @impl true
  def handle_connect(ctx) do
    {:ok, %{}, ctx}
  end

  @impl true
  def handle_event("toggle_editor", %{}, ctx) do
    visible = not ctx.assigns.visible

    {:noreply,
     ctx
     |> assign(visible: visible)
     |> reconfigure_smart_cell(editor: [visible: visible])}
  end

  @impl true
  def handle_editor_change(source, ctx) do
    {:ok, assign(ctx, source: source)}
  end

  @impl true
  def to_attrs(ctx) do
    %{"source" => ctx.assigns.source}
  end

  @impl true
  def to_source(attrs) do
    attrs["source"]
  end

  asset "main.js" do
    """
    export function init(ctx, payload) {
      root.innerHTML = `
        <button id="toggle">Hide/Show</button>
      `;

      ctx.root.querySelector(`#toggle`).addEventListener("click", (event) => {
        ctx.pushEvent("toggle_editor", {});
      });
    }
    """
  end
end

Kino.SmartCell.register(SmartCellWithEditorToggle)
```

</details>

### CODE REVIEW

**Review by josevalim — APPROVED** [review]

**Comment by mruoss** [comment]
love this! Thanks so much!

**Comment by mruoss** [comment]
But... shouldn't there be some frontend code that actually shows/hides the editor?

**Comment by jonatanklosko** [comment]
@mruoss when the user selects FLAME Kubernetes backend, the smart cell server will receive the change and then you call `reconfigure_smart_cell` to show the editor (and set the initial source). Does that make sense or am I missing something?

**Comment by mruoss** [comment]
It does make sense and I'd say it is what I'm donig. I'm setting `visible` to `false` initially. But the editor is visible nontheless. Then, toggling the backend (Fly/K8s) reconfigures the smart cell setting `visible` accordingly. But the editor is never hidden.

**Comment by jonatanklosko** [comment]
@mruoss did you pull Livebook main? :D

**Comment by mruoss** [comment]
works like a charm. My bad, sorry.

**Comment by jonatanklosko** [comment]
Perfect, and no worries!

**Pull request merged**
