### PR TITLE
Do automatic stream conversion on listen

### PR DESCRIPTION
**Pull request by josevalim**

### CODE REVIEW

**Comment by josevalim** [comment]
The main goal here is to reduce the learning curve. Telling folks they need to convert to a stream before listening is a bit too much, IMO.

**Comment by josevalim** [comment]
@jonatanklosko I understand your concerns now. WDYT about implementing enumerable for Kino.Input and Kino.Control and Kino.Control.stream + tagged_stream are basically mechanisms to merge and tag them? That keeps the API as is (which you want) and makes it more concise (which I want :D).

**Comment by jonatanklosko** [comment]
@josevalim Enumerable works for me!

**Comment by josevalim** [comment]
New PR incoming.

**Pull request closed without merging**
